openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /signup:
    post:
      summary: Create a account.
      description: Sign up by giving a name and a password
      parameters:
        - in: path
          name: name
          description: Name of the new user
          required: True
          schema:
            type: string
        - in: path
          name: password
          description: Password of the new user
          required: True
          schema:
            type: string
      tags:
        - authentification
      responses:
        '201':
          description: smtg
          content:
            application/form-data:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  password:
                    type: string
    get:
      summary:
      tags:
        - authentification
  /login:
    post:
      summary:
      tags:
        - authentification
    get:
      summary:
      tags:
        - authentification
  /logout:
    get:
      summary:
      tags:
        - authentification
  /:
    get:
      summary:
      tags:
        - main
  /profile:
    get:
      summary:
      tags:
        - main
  /groups/{group_name}:
    post:
      summary:
      tags:
        - main
    get:
      summary:
      tags:
        - main
  /groups/names:
    get:
      summary: Retrieve a list containing all the groups names
      tags:
        - main
      responses:
        '200':
          description: List of group names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
  /score_board:
    get:
      summary:
      tags:
        - main
  /match:
    post:
      summary: Create or modify the results of a particuliar match
      parameters:
        - in: query
          name: team1
          schema:
            type: string
          description: Name of the team 1
        - in: query
          name: team2
          schema:
            type: string
          description: Name of the team 2
      requestBody:
        required: true
        content:
            application/json:
              schema:
                type: array
                items:
                  description: result
                  type: integer
                minItems: 2
                maxItems: 2
      tags:
        - main
      responses:
        '201':
          description: smtg
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                minItems: 2
                maxItems: 2
    get:
      summary: Retrieve results of a particuliar match
      parameters:
        - in: query
          name: team1
          schema:
            type: string
          description: Name of the team 1
        - in: query
          name: team2
          schema:
            type: string
          description: Name of the team 2
      tags:
        - main
      responses:
        '201':
          description: smtg
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                minItems: 2
                maxItems: 2
